{
  "Role": {
    "sensitive": false,
    "type": "string",
    "value": "arn:aws:iam::${account}:role/migrations-ci"
  },
  "Tasks": {
    "sensitive": false,
    "value": {
      "import-fixtures-api": {
        "Cluster": "${cluster}",
        "LaunchType": "FARGATE",
        "NetworkConfiguration": {
          "AwsvpcConfiguration": {
            "SecurityGroups": [
              "${sec-group}"
            ],
            "Subnets": [
              "${subnets}"
            ]
          }
        },
        "TaskDefinition": "arn:aws:ecs:eu-west-1:${account}:task-definition/import-fixtures-api-${cluster}"
      },
      "migrate-api": {
        "Cluster": "${cluster}",
        "LaunchType": "FARGATE",
        "NetworkConfiguration": {
          "AwsvpcConfiguration": {
            "SecurityGroups": [
              "${sec-group}"
            ],
            "Subnets": [
              "${subnets}"
            ]
          }
        },
        "TaskDefinition": "arn:aws:ecs:eu-west-1:${account}:task-definition/migrate-api-${cluster}"
      },
      "reset-api": {
        "Cluster": "${cluster}",
        "LaunchType": "FARGATE",
        "NetworkConfiguration": {
          "AwsvpcConfiguration": {
            "SecurityGroups": [
              "${sec-group}"
            ],
            "Subnets": [
              "${subnets}"
            ]
          }
        },
        "TaskDefinition": "arn:aws:ecs:eu-west-1:${account}:task-definition/reset-api-${cluster}"
      },
      "ingest-cases": {
        "Cluster": "${cluster}",
        "LaunchType": "FARGATE",
        "NetworkConfiguration": {
          "AwsvpcConfiguration": {
            "SecurityGroups": [
              "${sec-group}"
            ],
            "Subnets": [
              "${subnets}"
            ]
          }
        },
        "TaskDefinition": "arn:aws:ecs:eu-west-1:${account}:task-definition/ingest-cases-${cluster}"
      },
      "migrate-membrane": {
        "Cluster": "${cluster}",
        "LaunchType": "FARGATE",
        "NetworkConfiguration": {
          "AwsvpcConfiguration": {
            "SecurityGroups": [
              "${sec-group-membrane}"
            ],
            "Subnets": [
              "${subnets}"
            ]
          }
        },
        "TaskDefinition": "arn:aws:ecs:eu-west-1:${account}:task-definition/migrate-membrane-${cluster}"
      },
      "import-fixtures-membrane": {
        "Cluster": "${cluster}",
        "LaunchType": "FARGATE",
        "NetworkConfiguration": {
          "AwsvpcConfiguration": {
            "SecurityGroups": [
              "${sec-group-membrane}"
            ],
            "Subnets": [
              "${subnets}"
            ]
          }
        },
        "TaskDefinition": "arn:aws:ecs:eu-west-1:${account}:task-definition/import-fixtures-membrane-${cluster}"
      },
      "reset-membrane": {
        "Cluster": "${cluster}",
        "LaunchType": "FARGATE",
        "NetworkConfiguration": {
          "AwsvpcConfiguration": {
            "SecurityGroups": [
              "${sec-group-membrane}"
            ],
            "Subnets": [
              "${subnets}"
            ]
          }
        },
        "TaskDefinition": "arn:aws:ecs:eu-west-1:${account}:task-definition/reset-membrane-${cluster}"
      },
      "behat-migration": {
        "Cluster": "${cluster}",
        "LaunchType": "FARGATE",
        "NetworkConfiguration": {
        "AwsvpcConfiguration": {
          "SecurityGroups": [
            "${sec-group}"
          ],
          "Subnets": [
            "${subnets}"
          ]
        }
        },
        "TaskDefinition": "arn:aws:ecs:eu-west-1:288342028542:task-definition/behat-migration-${cluster}"
      },
      "migration-prepare":{
        "Cluster":"${casrec-cluster}",
        "LaunchType":"FARGATE",
        "NetworkConfiguration":{
            "AwsvpcConfiguration":{
                "SecurityGroups":[
                    "${casrec-sec-group}"
                ],
                "Subnets":[
                    ${casrec-subnets}
                ]
            }
        },
        "Overrides": {
            "ContainerOverrides": [{
                "Name": "etl0",
                "Command": ["prepare/prepare.sh"]
            }]
        },
        "TaskDefinition":"${casrec-task-definition-prepare}"
      },
      "migration-load-casrec":{
        "Cluster":"${casrec-cluster}",
        "LaunchType":"FARGATE",
        "NetworkConfiguration":{
            "AwsvpcConfiguration":{
                "SecurityGroups":[
                    "${casrec-sec-group}"
                ],
                "Subnets":[
                    ${casrec-subnets}
                ]
            }
        },
        "Overrides": {
            "ContainerOverrides": [{
                "Name": "etl1",
                "Command": ["python3", "load_casrec_schema/app/app.py"]
            }]
        },
        "TaskDefinition":"${casrec-task-definition-load-casrec}"
      },
      "migration-transform":{
        "Cluster":"${casrec-cluster}",
        "LaunchType":"FARGATE",
        "NetworkConfiguration":{
            "AwsvpcConfiguration":{
                "SecurityGroups":[
                    "${casrec-sec-group}"
                ],
                "Subnets":[
                    ${casrec-subnets}
                ]
            }
        },
        "Overrides": {
            "ContainerOverrides": [{
                "Name": "etl2",
                "Command": ["transform_casrec/transform.sh"]
            }]
        },
        "TaskDefinition":"${casrec-task-definition-transform}"
      },
      "migration-integration":{
        "Cluster":"${casrec-cluster}",
        "LaunchType":"FARGATE",
        "NetworkConfiguration":{
            "AwsvpcConfiguration":{
                "SecurityGroups":[
                    "${casrec-sec-group}"
                ],
                "Subnets":[
                    ${casrec-subnets}
                ]
            }
        },
        "Overrides": {
            "ContainerOverrides": [{
                "Name": "etl3",
                "Command": ["integration/integration.sh"]
            }]
        },
        "TaskDefinition":"${casrec-task-definition-integration}"
      },
      "migration-load-sirius":{
        "Cluster":"${casrec-cluster}",
        "LaunchType":"FARGATE",
        "NetworkConfiguration":{
            "AwsvpcConfiguration":{
                "SecurityGroups":[
                    "${casrec-sec-group}"
                ],
                "Subnets":[
                    ${casrec-subnets}
                ]
            }
        },
        "Overrides": {
            "ContainerOverrides": [{
                "Name": "etl4",
                "Command": ["load_to_sirius/load_to_sirius.sh"]
            }]
        },
        "TaskDefinition":"${casrec-task-definition-load-sirius}"
      },
      "migration-validation":{
        "Cluster":"${casrec-cluster}",
        "LaunchType":"FARGATE",
        "NetworkConfiguration":{
            "AwsvpcConfiguration":{
                "SecurityGroups":[
                    "${casrec-sec-group}"
                ],
                "Subnets":[
                    ${casrec-subnets}
                ]
            }
        },
        "Overrides": {
            "ContainerOverrides": [{
                "Name": "etl5",
                "Command": ["validation/validate.sh"]
            }]
        },
        "TaskDefinition":"${casrec-task-definition-validation}"
      },
      "migration-response-api-tests":{
        "Cluster":"${casrec-cluster}",
        "LaunchType":"FARGATE",
        "NetworkConfiguration":{
            "AwsvpcConfiguration":{
                "SecurityGroups":[
                    "${casrec-sec-group}"
                ],
                "Subnets":[
                    ${casrec-subnets}
                ]
            }
        },
        "Overrides": {
            "ContainerOverrides": [{
                "Name": "etl5",
                "Command": ["validation/api_tests.sh"]
            }]
        },
        "TaskDefinition":"${casrec-task-definition-validation}"
      },
      "migration-functional-api-tests":{
        "Cluster":"${casrec-cluster}",
        "LaunchType":"FARGATE",
        "NetworkConfiguration":{
            "AwsvpcConfiguration":{
                "SecurityGroups":[
                    "${casrec-sec-group}"
                ],
                "Subnets":[
                    ${casrec-subnets}
                ]
            }
        },
        "Overrides": {
            "ContainerOverrides": [{
                "Name": "etl5",
                "Command": ["validation/functional_api_tests.sh"]
            }]
        },
        "TaskDefinition":"${casrec-task-definition-validation}"
      },
      "reset-elasticsearch": {
        "Cluster": "${cluster}",
        "LaunchType": "FARGATE",
        "NetworkConfiguration": {
          "AwsvpcConfiguration": {
            "SecurityGroups": [
              "${sec-group}"
            ],
            "Subnets": [
              "${subnets}"
            ]
          }
        },
        "TaskDefinition": "arn:aws:ecs:eu-west-1:${account}:task-definition/reset-elasticsearch-${cluster}"
      },
      "pull-case":{
        "Cluster":"${casrec-cluster}",
        "LaunchType":"FARGATE",
        "NetworkConfiguration":{
            "AwsvpcConfiguration":{
                "SecurityGroups":[
                    "${casrec-sec-group}"
                ],
                "Subnets":[
                    ${casrec-subnets}
                ]
            }
        },
        "TaskDefinition":"${casrec-task-definition-prepare}"
      },
      "reindex-elasticsearch-by-date": {
        "Cluster": "${cluster}",
        "LaunchType": "FARGATE",
        "NetworkConfiguration": {
          "AwsvpcConfiguration": {
            "SecurityGroups": [
              "${sec-group}"
            ],
            "Subnets": [
              "${subnets}"
            ]
          }
        },
        "TaskDefinition": "arn:aws:ecs:eu-west-1:${account}:task-definition/reindex-elasticsearch-by-date-${cluster}"
      },
      "elasticsearch-reindex": {
        "Cluster": "${cluster}",
        "LaunchType": "FARGATE",
        "NetworkConfiguration": {
          "AwsvpcConfiguration": {
            "SecurityGroups": [
              "${sec-group}"
            ],
            "Subnets": [
              "${subnets}"
            ]
          }
        },
        "TaskDefinition": "arn:aws:ecs:eu-west-1:${account}:task-definition/elasticsearch-reindex-${cluster}"
      }
    }
  }
}
