---
version: '3.6'
services:
  generate:
    build:
      context: ./mappings
      dockerfile: Dockerfile
    volumes:
      - ./mappings/app:/generate/app
      - ./migration_steps/shared/mapping_spreadsheet:/generate/mapping_spreadsheet
      - ./migration_steps/shared/mapping_definitions:/generate/mapping_definitions
  casrec_db:
    image: postgres:10.11
    ports:
      - 6666:5432
    environment:
      POSTGRES_USER: casrec
      POSTGRES_PASSWORD: casrec # pragma: allowlist secret
      POSTGRES_DB: casrecmigration
      PGPASSWORD: casrec # pragma: allowlist secret
  localstack:
    image: localstack/localstack:0.10.9
    ports:
        - 5572:4572
        - 5566:4566
    environment:
        - SERVICES=s3:4572
        - DEFAULT_REGION=eu-west-1
  load_s3:
    build:
      context: ./migration_steps
      dockerfile: load_s3-dockerfile
    environment:
      DEFAULT_CHUNK_SIZE: 20000
      CSV_DIR_SUFFIX: ./data/anon_data
      S3_URL: http://localstack:4572
    volumes:
      - ./data:/data
  initialise:
    build:
      context: ./migration_steps
      dockerfile: initialise-dockerfile
    environment:
      DEFAULT_CHUNK_SIZE: 500
      DB_USER: casrec
      DB_PASSWORD: casrec # pragma: allowlist secret
      DB_NAME: casrecmigration
      DB_HOST: casrec_db
      DB_PORT: 5432
      SIRIUS_DB_USER: api
      SIRIUS_DB_PASSWORD: api # pragma: allowlist secret
      SIRIUS_DB_NAME: api
      SIRIUS_DB_HOST: postgres-sirius
      SIRIUS_DB_PORT: 5432
      ENVIRONMENT: local
      ACCOUNT_NAME: local
      SIRIUS_ACCOUNT: NA
      S3_URL: http://localstack:4572
    depends_on: [casrec_db, postgres-sirius]
  load_casrec:
    build:
      context: ./migration_steps
      dockerfile: load_casrec-dockerfile
    environment:
      DEFAULT_CHUNK_SIZE: 500
      DB_USER: casrec
      DB_PASSWORD: casrec # pragma: allowlist secret
      DB_NAME: casrecmigration
      DB_HOST: casrec_db
      DB_PORT: 5432
      ENVIRONMENT: local
      ACCOUNT_NAME: local
      S3_PATH: anon
      SIRIUS_ACCOUNT: NA
      S3_URL: http://localstack:4572
    depends_on: [localstack, casrec_db]
  transform_casrec:
    build:
      context: ./migration_steps
      dockerfile: transform_casrec-dockerfile
    environment:
      DEFAULT_CHUNK_SIZE: 500
      DB_USER: casrec
      DB_PASSWORD: casrec # pragma: allowlist secret
      DB_NAME: casrecmigration
      DB_HOST: casrec_db
      DB_PORT: 5432
      ENVIRONMENT: local
    depends_on: [localstack, casrec_db]
  integration:
    build:
      context: ./migration_steps
      dockerfile: integration-dockerfile
    environment:
      DEFAULT_CHUNK_SIZE: 500
      DB_USER: casrec
      DB_PASSWORD: casrec # pragma: allowlist secret
      DB_NAME: casrecmigration
      DB_HOST: casrec_db
      DB_PORT: 5432
      SIRIUS_DB_USER: api
      SIRIUS_DB_PASSWORD: api # pragma: allowlist secret
      SIRIUS_DB_NAME: api
      SIRIUS_DB_HOST: postgres-sirius
      SIRIUS_DB_PORT: 5432
      ENVIRONMENT: local
    depends_on: [casrec_db, postgres-sirius]
  validation:
    build:
      context: ./migration_steps
      dockerfile: validation-dockerfile
    environment:
      DEFAULT_CHUNK_SIZE: 500
      DB_USER: casrec
      DB_PASSWORD: casrec # pragma: allowlist secret
      DB_NAME: casrecmigration
      DB_HOST: casrec_db
      DB_PORT: 5432
      SIRIUS_DB_USER: api
      SIRIUS_DB_PASSWORD: api # pragma: allowlist secret
      SIRIUS_DB_NAME: api
      SIRIUS_DB_HOST: postgres-sirius
      SIRIUS_DB_PORT: 5432
      ACCOUNT_NAME: local
      ENVIRONMENT: local
      SIRIUS_ACCOUNT: NA
      S3_URL: http://localstack:4572
      SIRIUS_FRONT_USER: case.manager@opgtest.com
    depends_on: [casrec_db, postgres-sirius]
  wait-for-it:
    build: ./wait-for-it
#  Please read the readme in ./sirius-snapshot before building the Sirius db
  postgres-sirius:
    image: postgres:10.11
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api # pragma: allowlist secret
      POSTGRES_DB: api
      PGPASSWORD: api # pragma: allowlist secret
  postgres-sirius-restore:
    image: postgres:10.11
    entrypoint: pg_restore
    volumes: ["./sirius_db/db_snapshots:/db_snapshots"]
    command:
      - /db_snapshots/api.backup
      - --clean
      - --if-exists
      - --host=postgres-sirius
      - --dbname=api
      - --username=api
      - -v
      - --format=custom
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api # pragma: allowlist secret
      PGPASSWORD: api # pragma: allowlist secret
      POSTGRES_DB: api
    depends_on: [postgres-sirius]
  postgres-sirius-post-lay-restore:
    image: postgres:10.11
    entrypoint: pg_restore
    volumes: ["./sirius_db/db_snapshots:/db_snapshots"]
    command:
      - /db_snapshots/api-post-lay.backup
      - --clean
      - --if-exists
      - --host=postgres-sirius
      - --dbname=api
      - --username=api
      - -v
      - --format=custom
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api # pragma: allowlist secret
      PGPASSWORD: api # pragma: allowlist secret
      POSTGRES_DB: api
    depends_on: [postgres-sirius]
  postgres-sirius-post-p2-restore:
    image: postgres:10.11
    entrypoint: pg_restore
    volumes: ["./sirius_db/db_snapshots:/db_snapshots"]
    command:
      - /db_snapshots/api-post-p2-m2.backup
      - --clean
      - --if-exists
      - --host=postgres-sirius
      - --dbname=api
      - --username=api
      - -v
      - --format=custom
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api # pragma: allowlist secret
      PGPASSWORD: api # pragma: allowlist secret
      POSTGRES_DB: api
    depends_on: [postgres-sirius]
  postgres-sirius-backup:
    image: postgres:10.20
    entrypoint: pg_dump
    command:
      - --host=postgres-sirius
      - --dbname=api
      - --username=api
      - --file=/db_snapshots/api-post-p2-m2.backup
      - -b
      - --format=custom
    volumes: ["./sirius_db/db_snapshots:/db_snapshots"]
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api # pragma: allowlist secret
      PGPASSWORD: api # pragma: allowlist secret
      POSTGRES_DB: api
    depends_on: [postgres-sirius]
  load_to_target:
    build:
      context: ./migration_steps
      dockerfile: load_to_target-dockerfile
    environment:
      DEFAULT_CHUNK_SIZE: 500
      DB_USER: casrec
      DB_PASSWORD: casrec # pragma: allowlist secret
      DB_NAME: casrecmigration
      DB_HOST: casrec_db
      DB_PORT: 5432
      SIRIUS_DB_USER: api
      SIRIUS_DB_PASSWORD: api # pragma: allowlist secret
      SIRIUS_DB_NAME: api
      SIRIUS_DB_HOST: postgres-sirius
      SIRIUS_DB_PORT: 5432
      ENVIRONMENT: local
    depends_on: [casrec_db, postgres-sirius]
  unit_tests:
    build:
      context: ./migration_steps
      dockerfile: unit-tests-dockerfile
    environment:
      ENVIRONMENT: local
