version: '3.6'
services:
  case_to_s3:
    build:
      context: scripts/case_details_to_s3
      dockerfile: Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
      ENVIRONMENT: preproduction
    volumes:
      - ./scripts/case_details_to_s3/case_details_to_s3.py:/case_details_to_s3.py
      - ./terraform:/terraform
  task_runner:
    build:
      context: ./scripts/ecs_task_runner
      dockerfile: Dockerfile
    environment:
      ENVIRONMENT: preproduction
      WORKSPACE: preproduction
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
    volumes:
      - ./scripts/ecs_task_runner/run_ecs_task.py:/run_ecs_task.py
      - ./scripts/ecs_task_runner/run_ecs_task.sh:/run_ecs_task.sh
      - ./terraform:/terraform
  sync_mapping_json:
    build:
      context: ./scripts/sync_mapping_json
      dockerfile: Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
    volumes:
      - ./migration_steps/shared:/migration_steps/shared
      - ./scripts/sync_mapping_json/sync_mapping_json.py:/scripts/sync_mapping_json/sync_mapping_json.py
  migrate_tagged_version:
    build:
      context: ./scripts/migrate_tagged_version
      dockerfile: Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
    volumes:
      - ./scripts/migrate_tagged_version/app.py:/migrate_tagged_version/app.py
