version: '3.6'
services:
  postgres-api:
    image: postgres:10.11
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
      POSTGRES_DB: api
      PGPASSWORD: api
  postgres-api-restore:
    image: postgres:10.11
    entrypoint: pg_restore
    volumes: ["./sirius-snapshot:/sirius-snapshot"]
    command:
      - /sirius-snapshot/api.backup
      - --clean
      - --if-exists
      - --host=postgres-api
      - --dbname=api
      - --username=api
      - -v
      - --format=custom
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
      PGPASSWORD: api
      POSTGRES_DB: api
    depends_on: [postgres-api]
  casrec_db:
    image: postgres:10.11
    ports:
    - 6666:5432
    volumes:
      - ./casrec_data/create_db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_USER: casrec
      POSTGRES_PASSWORD: casrec
      POSTGRES_DB: casrec
      PGPASSWORD: casrec


