version: "3.6"

#docker-compose.override.yml is loaded and merged with docker-compose.yml by default when calling docker-compose up.
#This file won't be merged when using docker-compose -f docker-compose.yml up (or using any other compose file).
services:

  load_s3:
    volumes:
      - ./migration_steps/load_s3/load_s3_local.py:/load_s3_local.py

  load_casrec:
    volumes:
      - ./migration_steps/load_casrec/app:/app

  transform_casrec:
    volumes:
      - ./migration_steps/transform_casrec/app/:/app
      - ./migration_steps/shared:/shared

  prepare_load:
    volumes:
      - ./migration_steps/prepare_load/fixtures:/prepare_load/fixtures
      - ./migration_steps/prepare_load/merge_target_ids:/prepare_load/merge_target_ids
      - ./migration_steps/prepare_load/schema_setup:/prepare_load/schema_setup
      - ./migration_steps/prepare_load/prepare_target:/prepare_load/prepare_target
      - ./migration_steps/prepare_load/prepare_load.sh:/prepare_load/prepare_load.sh
      - ./migration_steps/shared:/shared

  load_to_target:
    volumes:
      - ./migration_steps/load_to_target/app:/app
      - ./migration_steps/shared:/shared
