version: '3.6'
services:
  etl1:
    image: ${AWS_REGISTRY}/casrec-migration/etl1:${VERSION}
    build:
      context: ./migration_steps
      dockerfile: load_casrec-dockerfile
  etl2:
    image: ${AWS_REGISTRY}/casrec-migration/etl2:${VERSION}
    build:
      context: ./migration_steps
      dockerfile: transform_casrec-dockerfile
  etl3:
    image: ${AWS_REGISTRY}/casrec-migration/etl3:${VERSION}
    build:
      context: ./migration_steps
      dockerfile: integration-dockerfile
  etl4:
    image: ${AWS_REGISTRY}/casrec-migration/etl4:${VERSION}
    build:
      context: ./migration_steps
      dockerfile: load_to_target-dockerfile
