version: "3.6"

#docker-compose.override.yml is loaded and merged with docker-compose.yml by default when calling docker-compose up.
#This file won't be merged when using docker-compose -f docker-compose.yml up (or using any other compose file).
services:

  load_s3:
    volumes:
      - ./migration_steps/load_s3/load_s3_local.py:/load_s3_local.py

  prepare:
    volumes:
      - ./migration_steps/prepare/prepare.sh:/prepare/prepare.sh
      - ./migration_steps/prepare/prepare_target:/prepare/prepare_target
      - ./migration_steps/prepare/create_stage_schema:/prepare/create_stage_schema
      - ./migration_steps/shared:/shared

  load_casrec:
    volumes:
      - ./migration_steps/load_casrec/app:/app

  postgres-sirius:
    volumes:
      - ./sirius_db/config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf

  transform_casrec:
    volumes:
      - ./migration_steps/transform_casrec/app/:/app
      - ./migration_steps/shared:/shared

  integration:
    volumes:
      - ./migration_steps/integration/fixtures:/integration/fixtures
      - ./migration_steps/integration/merge_target_ids:/integration/merge_target_ids
      - ./migration_steps/integration/schema_setup:/integration/schema_setup
      - ./migration_steps/integration/integration.sh:/integration/integration.sh
      - ./migration_steps/shared:/shared

  load_to_target:
    volumes:
      - ./migration_steps/audit:/audit
      - ./migration_steps/load_to_target/app:/app
      - ./migration_steps/shared:/shared

  validation:
    volumes:
      - ./migration_steps/validation/validate_db:/validation/validate_db
      - ./migration_steps/validation/validate.sh:/validation/validate.sh
      - ./migration_steps/shared:/shared
