version: '3.6'
services:
  casrec_db:
    image: postgres:10.7
    ports:
      - 6666:5432
    environment:
      POSTGRES_USER: casrec
      POSTGRES_PASSWORD: casrec # pragma: allowlist secret
      POSTGRES_DB: casrecmigration
      PGPASSWORD: casrec # pragma: allowlist secret
  localstack:
    image: localstack/localstack:0.10.9
    ports:
        - 4572:4572
        - 4566:4566
    environment:
        - SERVICES=s3:4572
        - DEFAULT_REGION=eu-west-1
  load_s3:
    build:
      context: ./etl1
      dockerfile: DockerfileS3Load
    volumes:
      - ./etl1/anon_data:/anon_data
  load_casrec:
    build:
      context: ./etl1
      dockerfile: Dockerfile
    environment:
      DB_PASSWORD: casrec # pragma: allowlist secret
      DB_NAME: casrecmigration
      DB_HOST: casrec_db
      DB_PORT: 5432
      ENVIRONMENT: local
      S3_PATH: anon
    depends_on: [localstack, casrec_db]
  transform_casrec:
    build:
      context: ./etl2
      dockerfile: Dockerfile
    environment:
      DB_PASSWORD: casrec # pragma: allowlist secret
      DB_NAME: casrecmigration
      DB_HOST: casrec_db
      DB_PORT: 5432
      ENVIRONMENT: docker
    depends_on: [localstack, casrec_db]
  wait-for-it:
    build: ./wait-for-it
#  Please read the readme in ./sirius-snapshot before building the Sirius db
  postgres-sirius:
    image: postgres:10.11
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
      POSTGRES_DB: api
      PGPASSWORD: api
  postgres-sirius-restore:
    image: postgres:10.11
    entrypoint: pg_restore
    volumes: ["./db-snapshots:/sirius-snapshot"]
    command:
      - /db-snapshots/api.backup
      - --clean
      - --if-exists
      - --host=postgres-sirius
      - --dbname=api
      - --username=api
      - -v
      - --format=custom
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
      PGPASSWORD: api
      POSTGRES_DB: api
    depends_on: [postgres-sirius]
  rationalise:
    build:
      context: ./etl3
      dockerfile: Dockerfile
    environment:
      DB_PASSWORD: casrec # pragma: allowlist secret
      DB_NAME: casrecmigration
      DB_HOST: casrec_db
      DB_PORT: 5432
      SIRIUS_DB_PASSWORD: api # pragma: allowlist secret
      SIRIUS_DB_NAME: api
      SIRIUS_DB_HOST: postgres-sirius
      SIRIUS_DB_PORT: 5432
      ENVIRONMENT: local
    depends_on: [casrec_db]
