version: '3.6'
services:
  casrec_db:
    build:
      context: ./casrec_db
      dockerfile: Dockerfile
    ports:
      - 6666:5432
    environment:
      POSTGRES_USER: casrec
      POSTGRES_PASSWORD: casrec # pragma: allowlist secret
      POSTGRES_DB: casrecmigration
      PGPASSWORD: casrec # pragma: allowlist secret
  localstack:
    image: localstack/localstack:0.10.9
    ports:
        - 4572:4572
    environment:
        - SERVICES=s3:4572
        - DEFAULT_REGION=eu-west-1
  load_casrec:
    build:
      context: ./etl1
      dockerfile: Dockerfile
    environment:
      DB_PASSWORD: casrec # pragma: allowlist secret
      DB_NAME: casrecmigration
      DB_HOST: casrec_db
      DB_PORT: 5432
      ENVIRONMENT: local
    depends_on: [localstack, casrec_db]
#
# We can put this back in when we know how we're using it!
#
#  postgres-api:
#    image: postgres:10.11
#    ports:
#      - 5555:5432
#    environment:
#      POSTGRES_USER: api
#      POSTGRES_PASSWORD: api
#      POSTGRES_DB: api
#      PGPASSWORD: api
#  postgres-api-restore:
#    image: postgres:10.11
#    entrypoint: pg_restore
#    volumes: ["./sirius-snapshot:/sirius-snapshot"]
#    command:
#      - /sirius-snapshot/api.backup
#      - --clean
#      - --if-exists
#      - --host=postgres-api
#      - --dbname=api
#      - --username=api
#      - -v
#      - --format=custom
#    environment:
#      POSTGRES_USER: api
#      POSTGRES_PASSWORD: api
#      PGPASSWORD: api
#      POSTGRES_DB: api
#    depends_on: [postgres-api]
