version: '3.6'
services:
  etl1:
    image: ${AWS_REGISTRY}/casrec-migration/load_casrec:${VERSION}
    build: migration_steps/load_casrec
  etl2:
    image: ${AWS_REGISTRY}/casrec-migration/transform_casrec:${VERSION}
    build: migration_steps/transform_casrec
  etl3:
    image: ${AWS_REGISTRY}/casrec-migration/acquire_target_ids:${VERSION}
    build: migration_steps/acquire_target_ids
  etl4:
    image: ${AWS_REGISTRY}/casrec-migration/etl4:${VERSION}
    build: ./etl4
