version: "3.8"
services:
    generate:
        build: .
        volumes:
            - ./app:/generate/app
            - ./mapping_spreadsheet:/generate/mapping_spreadsheet
            - ./mapping_definitions:/generate/mapping_definitions
