version: '3.6'
services:
  etl1:
    image: ${AWS_REGISTRY}/casrec-migration/etl1:${VERSION}
    build: ./etl1
  etl2:
    image: ${AWS_REGISTRY}/casrec-migration/etl2:${VERSION}
    build: ./etl2
  etl3:
    image: ${AWS_REGISTRY}/casrec-migration/etl3:${VERSION}
    build: ./etl3
  etl4:
    image: ${AWS_REGISTRY}/casrec-migration/etl4:${VERSION}
    build: ./etl4
