version: "3.6"

#docker-compose.override.yml is loaded and merged with docker-compose.yml by default when calling docker-compose up.
#This file won't be merged when using docker-compose -f docker-compose.yml up (or using any other compose file).
services:
  prepare:
    image: ${AWS_REGISTRY}/casrec-migration/etl0:${VERSION}

  load_casrec:
    image: ${AWS_REGISTRY}/casrec-migration/etl1:${VERSION}
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      ENVIRONMENT: development
      ACCOUNT_NAME: development
      CI: $CI
      SIRIUS_ACCOUNT: 288342028542

  transform_casrec:
    image: ${AWS_REGISTRY}/casrec-migration/etl2:${VERSION}

  integration:
    image: ${AWS_REGISTRY}/casrec-migration/etl3:${VERSION}

  load_to_target:
    image: ${AWS_REGISTRY}/casrec-migration/etl4:${VERSION}

  validation:
    image: ${AWS_REGISTRY}/casrec-migration/etl5:${VERSION}
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      CI: $CI
      SIRIUS_ACCOUNT: 288342028542
