version: '3.6'
services:
  case_to_s3:
    build:
      context: ./casrec_data/run_ecs_task
      dockerfile: Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
      ENVIRONMENT: preproduction
    volumes:
      - ./casrec_data/run_ecs_task/run_ecs_task.py:/run_ecs_task.py
      - ./terraform:/terraform
