version: '3.6'
services:
  etl1:
    image: ${AWS_REGISTRY}/casrec-migration/etl1:${VERSION}
    build: migration_steps/load_casrec
  etl2:
    image: ${AWS_REGISTRY}/casrec-migration/etl2:${VERSION}
    build: migration_steps/transform_casrec
  etl3:
    image: ${AWS_REGISTRY}/casrec-migration/etl3:${VERSION}
    build: migration_steps/acquire_target_ids
  etl4:
    image: ${AWS_REGISTRY}/casrec-migration/etl4:${VERSION}
    build: migration_steps/load_to_target
