{
  "Role": {
    "sensitive": false,
    "type": "string",
    "value": "arn:aws:iam::${account}:role/sirius-ci"
  },
  "Tasks": {
    "sensitive": false,
    "value": {
      "pull-case": {
        "Cluster": "${cluster}",
        "LaunchType": "FARGATE",
        "NetworkConfiguration": {
          "AwsvpcConfiguration": {
            "SecurityGroups": [
              "${sec_group}"
            ],
            "Subnets": [
              ${subnets}
            ]
          }
        },
        "TaskDefinition": "${task-definition}"
      }
    }
  }
}
