{
  "Role": {
    "sensitive": false,
    "type": "string",
    "value": "arn:aws:iam::${account}:role/sirius-ci"
  },
  "Tasks": {
    "sensitive": false,
    "value": {
      "import-fixtures-api": {
        "Cluster": "${cluster}",
        "LaunchType": "FARGATE",
        "NetworkConfiguration": {
          "AwsvpcConfiguration": {
            "SecurityGroups": [
              "${sec_group}"
            ],
            "Subnets": [
              "${subnets}"
            ]
          }
        },
        "TaskDefinition": "arn:aws:ecs:eu-west-1:${account}:task-definition/import-fixtures-api-${cluster}"
      },
      "migrate-api": {
        "Cluster": "${cluster}",
        "LaunchType": "FARGATE",
        "NetworkConfiguration": {
          "AwsvpcConfiguration": {
            "SecurityGroups": [
              "${sec_group}"
            ],
            "Subnets": [
              "${subnets}"
            ]
          }
        },
        "TaskDefinition": "arn:aws:ecs:eu-west-1:${account}:task-definition/migrate-api-${cluster}"
      },
      "reset-api": {
        "Cluster": "${cluster}",
        "LaunchType": "FARGATE",
        "NetworkConfiguration": {
          "AwsvpcConfiguration": {
            "SecurityGroups": [
              "${sec_group}"
            ],
            "Subnets": [
              "${subnets}"
            ]
          }
        },
        "TaskDefinition": "arn:aws:ecs:eu-west-1:${account}:task-definition/reset-api-${cluster}"
      },
      "ingest-cases": {
        "Cluster": "${cluster}",
        "LaunchType": "FARGATE",
        "NetworkConfiguration": {
          "AwsvpcConfiguration": {
            "SecurityGroups": [
              "${sec_group}"
            ],
            "Subnets": [
              "${subnets}"
            ]
          }
        },
        "TaskDefinition": "arn:aws:ecs:eu-west-1:${account}:task-definition/ingest-cases-${cluster}"
      },
      "ingest-users": {
        "Cluster": "${cluster}",
        "LaunchType": "FARGATE",
        "NetworkConfiguration": {
          "AwsvpcConfiguration": {
            "SecurityGroups": [
              "${sec_group}"
            ],
            "Subnets": [
              "${subnets}"
            ]
          }
        },
        "TaskDefinition": "arn:aws:ecs:eu-west-1:${account}:task-definition/ingest-users-${cluster}"
      },
      "migrate-membrane": {
        "Cluster": "${cluster}",
        "LaunchType": "FARGATE",
        "NetworkConfiguration": {
          "AwsvpcConfiguration": {
            "SecurityGroups": [
              "${sec_group_membrane}"
            ],
            "Subnets": [
              "${subnets}"
            ]
          }
        },
        "TaskDefinition": "arn:aws:ecs:eu-west-1:${account}:task-definition/migrate-membrane-${cluster}"
      },
      "import-fixtures-membrane": {
        "Cluster": "${cluster}",
        "LaunchType": "FARGATE",
        "NetworkConfiguration": {
          "AwsvpcConfiguration": {
            "SecurityGroups": [
              "${sec_group_membrane}"
            ],
            "Subnets": [
              "${subnets}"
            ]
          }
        },
        "TaskDefinition": "arn:aws:ecs:eu-west-1:${account}:task-definition/import-fixtures-membrane-${cluster}"
      },
      "reset-membrane": {
        "Cluster": "${cluster}",
        "LaunchType": "FARGATE",
        "NetworkConfiguration": {
          "AwsvpcConfiguration": {
            "SecurityGroups": [
              "${sec_group_membrane}"
            ],
            "Subnets": [
              "${subnets}"
            ]
          }
        },
        "TaskDefinition": "arn:aws:ecs:eu-west-1:${account}:task-definition/reset-membrane-${cluster}"
      },
      "behat-migration": {
        "Cluster": "${cluster}",
        "LaunchType": "FARGATE",
        "NetworkConfiguration": {
        "AwsvpcConfiguration": {
          "SecurityGroups": [
            "${sec_group}"
          ],
          "Subnets": [
            "${subnets}"
          ]
        }
        },
        "TaskDefinition": "arn:aws:ecs:eu-west-1:288342028542:task-definition/behat-migration-${cluster}"
      },
      "reset-elasticsearch": {
        "Cluster": "${cluster}",
        "LaunchType": "FARGATE",
        "NetworkConfiguration": {
          "AwsvpcConfiguration": {
            "SecurityGroups": [
              "${sec_group}"
            ],
            "Subnets": [
              "${subnets}"
            ]
          }
        },
        "TaskDefinition": "arn:aws:ecs:eu-west-1:${account}:task-definition/reset-elasticsearch-${cluster}"
      }
    }
  }
}
