-- LIST OF EXTRA STATEMENTS THAT MAY BE NEEDED BUT ARE NOT CURRENTLY USED
--delete from events where source_person_id in (select id from persons where clientsource = 'SKELETON');
--delete from events where owning_donor_id in (select id from persons where clientsource = 'SKELETON');
--delete from persons where fee_payer_id in (select id from persons where clientsource = 'SKELETON');
