name: Load Casrec DB


permissions:
  actions: read
  checks: read
  contents: none
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none

on:
  pull_request:
    paths:
      - "migration_steps/load_casrec**"
    branches:
      - main
  push:
    paths:
      - "migration_steps/load_casrec**"
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./terraform/shared

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      - uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure AWS Credentials For Terraform
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          role-session-name: GitHubActionsOrgInfra

      - name: Lint Terraform
        id: tf_lint
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: |
          terraform init --upgrade -input=false

      - name: Terraform Plan
        run: |
          terraform plan -lock-timeout=300s -input=false -parallelism=30

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          terraform apply -lock-timeout=300s -input=false -auto-approve -parallelism=30
